config/routes.rb
InspireMe::Application.routes.draw do

  root :to => 'welcome#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  resources :passwordresets
  resources :users
  resources :sessions
  resources :home
  resources :ideas
  resources :lists
  resources :password_resets
  resources :friendships
  resources :listings


end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :description, :private, :assets_attributes, :user_id, :created_at

  belongs_to :user
  has_many :ideas, :dependent => :destroy
  has_many :assets, :dependent => :destroy
  has_many :listings, :dependent => :destroy

  accepts_nested_attributes_for :assets, :allow_destroy => true

  validates_presence_of :name
  validates_presence_of :description

  def self.newcontent(user)
    where("updated_at > ?", user.last_logged_in)
  end



end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    list_sort_order(params[:so])
    @lists = @mylists
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find_by_name(params[:id])
    list_sort_order(params[:so])
    @Lassets = Asset.find_all_by_list_id(@list.id)
    @ideas = @list.ideas
    @followers = Listing.followers(@list.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
    list_sort_order(params[:so])
    1.times {@list.assets.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find_by_name(params[:id])
    list_sort_order(params[:so])
    1.times {@list.assets.build}
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_path(:id => @list.name), notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find_by_id(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to list_path(:id => @list.name),  notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find_by_name(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_path, notice: 'List has been deleted' }
      format.json { head :no_content }
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, :class=>"form-horizontal",  :html => { :multipart => true } do |f| %>

    <%= render "shared/error_messages", :target => @list %>

  <div class="control-group">
    <%= f.label :name, "List name", :class=>"control-label" %>
    <%= f.text_field :name, :class=>"controls" %>
  </div>

  <div class="control-group">
    <%= f.label :description, :class=>"control-label" %>
    <%= f.text_area :description, :rows=>"5", :columns=>"30", :class=>"controls" %>
  </div>

  <div class="control-group">
    <%= f.check_box :private, :class=>"controls" %><%= f.label :private, :class=>"checkbox inline control-label" %>
  </div>

    <div class="control-group">
       Choose new logo
      <%= f.fields_for :assets do |asset_fields| %>
          <% if  asset_fields.object.new_record? %>
              <p><%= asset_fields.file_field :asset %></p>
          <% end %>
      <% end %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list <%= @list.name %></h1>

<%= form_for @list, :class=>"form-horizontal",  :html => { :multipart => true } do |f| %>
    <%= render "shared/error_messages", :target => @list %>

    <div class="control-group">

    </div>
    <span class ="clearfix"></span>


    <div class="control-group">

      <%= f.fields_for :assets do |asset_fields| %>

          <% unless asset_fields.object.new_record? %>
              <p>
                <%= image_tag(asset_fields.object.asset.url(:thumb), :class=> 'img-polaroid') %>
                <span>Tick to remove </span><%= asset_fields.check_box :_destroy %>
              </p>
          <% end %>
      <% end %>
    </div>

    <div class="control-group">
      Choose new logo
      <%= f.fields_for :assets do |asset_fields| %>
          <% if  asset_fields.object.new_record? %>
              <p><%= asset_fields.file_field :asset %></p>
          <% end %>
      <% end %>
    </div>
    <div class="control-group">
      <%= f.label :name, "List name", :class=>"control-label" %>
      <%= f.text_field :name, :class=>"controls" %>
    </div>

    <div class="control-group">
      <%= f.label :description, :class=>"control-label" %>
      <%= f.text_area :description, :rows=>"5", :columns=>"30", :class=>"controls" %>
    </div>

    <div class="control-group">
      <%= f.check_box :private, :class=>"controls" %><%= f.label :private, :class=>"checkbox inline control-label" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/lists/index.html.erb
<h1 class="page-header">My Lists</h1>
<p>sort by:<%= link_to "A-Z",lists_path(:so=>"a") %> / <%= link_to "Z-A",lists_path(:so=>"z") %> / <%= link_to "newest",lists_path(:so=>"0") %> / <%= link_to "oldest",lists_path(:so=>"9") %></p>
<ul class="thumbnails">
    <% @lists.each do |list| %>
      <% @Logo = Asset.gather_logo_for_list(list.id)  %>
        <li class ="span3">
            <div class="thumbnail">
              <h3>
                <% @Logo.each do |asset|  %>
                    <%= link_to image_tag(asset.asset.url(:thumb), :class=> 'img-polaroid'), list_path(:id => list.name) %>
                <% end %>
                <%= link_to list.name.titlecase, list_path(:id => list.name) %>
                <% if list.private %>
                    <span class="pull-right"><i class="icon-lock"></i></span>
                <% end %>
              </h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
               </p>
              <% if list.user_id !=current_user.id %>
                <%= link_to "Follow", root_url, :class=>"btn pull-right btn-link btn-small" %>
              <% end %>
              <p>
                <% if list.user_id == current_user.id %>
                    <%=  link_to '<i class="icon-pencil"></i>'.html_safe,edit_list_path(:id => list.name), :title=>"Edit list" %>
                <% end %>
              <%=  link_to '<i class="icon-zoom-in"></i>'.html_safe, list_path(:id => list.name), :title=>"view list" %>
                <% if list.user_id !=current_user.id %>
                    <%=  link_to '<i class="icon-flag"></i>'.html_safe,root_url, :title=>"Report list" %>
                <% end %>
                <% if list.user_id == current_user.id %>
                    <%=  link_to '<i class="icon-trash"></i>'.html_safe,list_path(:id => list.name), :method => :delete, :title=>"Delete list" %>
                <% end %>
              </p>
            </div>
        </li>
    <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1 class="page-header">
    <% @Lassets.each do |asset|  %>
      <%= link_to image_tag(asset.asset.url(:thumb), :class=> 'img-polaroid'),asset.asset.url(:original) %>
    <% end %>
  <%= @list.name.titlecase %> list
  <% if @list.private %>
      <span class="pull-right"><i class="icon-lock"></i></span>
  <% end %>
  <div class="btn-group">
    <p class="pull-right">
      <%= link_to "Follow", listings_path(:id=>@list.id), :method => "post", :class=>"btn btn-mini" %> <%= link_to "Edit",edit_list_path(:id => @list.name), :class=>"btn btn-mini" %> <%= link_to "Delete",root_url, :class=>"btn btn-mini" %>
      </p>
  </div>
    <p><small><%= @list.description %></small></p>
</h1>

<div>
    <h5>
      This list was created
      <%= distance_of_time_in_words_to_now(@list.created_at) %> ago
    </h5>
    <h5>
      And was last modified
      <%= distance_of_time_in_words_to_now(@list.updated_at) %> ago
    </h5>

  <h5>Number of followers:<%= @followers.count %></h5>
  <% @followers.each do |fl| %>
    <%= fl.user.displayname %>
  <% end %>
  <hr />


</div>
<span class ="clearfix"></span>
<p><%=  link_to "Create New Content", new_idea_path(:listid=> @list.id) %></p>
<p>Existing Content</p>
<ul class="thumbnails">
    <% @ideas.each do |idea| %>
      <% @Passets = Asset.gather_images_for_idea(idea.id)  %>
          <li class ="span3">
            <div class="thumbnail">

              <% @Passets.each do |asset|  %>
                  <%=image_tag(asset.asset.url(:thumb), :class=> 'pull-left img-polaroid') %>
              <% end %>

              <%= link_to idea.title, idea_path(:id => idea.title) %>
              <p><%= idea.content %></p>
              <p>
                <%=  link_to '<i class="icon-pencil"></i>'.html_safe,edit_idea_path(:id => idea.title), :title=>"Edit idea" %>
                <%=  link_to '<i class="icon-zoom-in"></i>'.html_safe, idea_path(:id => idea.title), :title=>"view idea" %>
                <%=  link_to '<i class="icon-flag"></i>'.html_safe,root_url, :title=>"Report idea" %>
                <%=  link_to '<i class="icon-trash"></i>'.html_safe,root_url, :title=>"Delete idea" %>
              </p>
            </div>

          </li>
    <% end %>
</ul>