config/routes.rb
InspireMe::Application.routes.draw do

  root :to => 'welcome#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  resources :passwordresets
  resources :users
  resources :sessions
  resources :home
  resources :ideas
  resources :lists
  resources :password_resets
  resources :friendships
  resources :listings


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :first_name, :surname, :description, :facebook_id, :twitter_id, :avatar_url, :website, :displayname, :assets_attributes
  has_secure_password
  has_many :lists
  has_many :assets

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :listings
  has_many :lists, :through => :listings


  accepts_nested_attributes_for :assets, :allow_destroy => true

  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => "create"
  validates_uniqueness_of :email, :on => "create", :message => "is already in use."
  validates_presence_of :displayname, :on => "create"
  validates_uniqueness_of :displayname, :on => "create", :message => "is already taken."

  before_create {generate_token(:auth_token)}

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def self.gather_friends_friend_details(friend)
    find_by_id(friend)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'
  def new
    @user = User.new
    1.times {@user.assets.build}
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice =>"Signed up"
    else
      render "new"
    end
  end

  def show
    @user = User.find_by_displayname(params[:id])
    @listings = Listing.find_all_by_user_id(params[:id])
  end

  def edit
    @user = User.find_by_displayname(current_user.displayname)
    @allusers = User.all
    @listings = Listing.find_all_by_user_id(current_user.id)
    1.times {@user.assets.build}
  end

  def update
    @user = User.find_by_displayname(current_user.displayname)

    if @user.update_attributes(params[:user])

       redirect_to home_path(:id => current_user.displayname), :notice => "Updated"
    else
      redirect_to home_path(:id => current_user.displayname), :alert => "Something went wrong, please try again"
    end
  end

  def destroy
    @user = User.find_by_displayname(current_user.displayname)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit-tabs-left-panel.html.erb
<div class="span12">
  <%= form_for @user, :multipart => :true do |user| %>
      <div class="form-horizontal">
        <%= render "shared/error_messages", :target => @user %>
        <div class="tabbable tabs-left">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#tab1" data-toggle="tab">Profile</a></li>
            <li><a href="#tab2" data-toggle="tab">Account Settings</a></li>
            <li><a href="#tab3" data-toggle="tab">Notifications</a></li>
            <li><a href="#tab4" data-toggle="tab">Subscriptions</a></li>
          </ul>
          <div class="tab-content">
            <%= render :partial => 'user_settings_tab1', :locals => { :user => user }%>
            <%= render :partial => 'user_settings_tab2', :locals => { :user => user } %>
            <%= render :partial => 'user_settings_tab3', :locals => { :user => user } %>
            <%= render :partial => 'user_settings_tab4', :locals => { :user => user } %>
          </div>
        </div>
        <div class="user-button-actions">
          <%= user.submit "Update", :class=>"controls btn btn-success btn-large" %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_navbar.html.erb
<% content_for :navigation do %>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Front Page", root_url %></li>

            </ul>
            <% if current_user %>
                <%= render :partial => 'layouts/user-drop-down-menu' %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
<% end %>

<%= content_for :navigation if current_user %>

app/views/users/_user_settings_tab1.html.erb
<div class="tab-pane active" id="tab1">
  <h2>Profile Settings </h2>
  <div class="control-group">
    <%= user.label :displayname, "Displayed Name", :class=>"control-label" %>
    <%= user.text_field :displayname, :class=>"controls" %>
  </div>
  <div class="control-group">
    <%= user.label :avatar_url, "Avatar", :class=>"control-label" %>
    <div class="control-group">
      <%= user.fields_for :assets do |asset_fields| %>
          <% if  asset_fields.object.new_record? %>
              <p><%= asset_fields.file_field :asset %></p>
          <% end %>
      <% end %>
    </div>
    <div class="control-group">
      <%= user.fields_for :assets do |asset_fields| %>
          <% unless asset_fields.object.new_record? %>
              <p>
                <%= image_tag(asset_fields.object.asset.url(:thumb), :class=> 'img-polaroid') %>
                <span>Remove </span><%= asset_fields.check_box :_destroy %>
                File name:<%= asset_fields.object.asset_file_name  %>
              </p>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= user.label :description, :class=>"control-label" %>
    <%= user.text_area :description, :rows => 5, :cols => 25, :class=>"controls" %>
  </div>
  <div class="control-group">
    <%= user.label :facebook, :class=>"control-label" %>
    <%= user.text_field :facebook_id, :class=>"controls" %>
  </div>
  <div class="control-group ">
    <%= user.label :twitter, :class=>"control-label" %>
    <div class="input-prepend">
      <span class="add-on controls">@</span>
      <%= user.text_field :twitter_id, :class=>"span2", :id=>"prependedInput"%>
    </div>
  </div>
  <div class="control-group">
    <%= user.label :website, :class=>"control-label" %>
    <%= user.text_field :website, :class=>"controls", :placeholder => "http://" %>
  </div>
</div>

app/views/users/_user_settings_tab2.html.erb
<div class="tab-pane" id="tab2">
  <h2>Account Settings</h2>
  <div class="control-group">
    <%= user.label :firstname, :class=>"control-label"  %>
    <%= user.text_field :first_name, :class=>"controls" %>
  </div>
  <div class="control-group">
    <%= user.label :surname, :class=>"control-label" %>
    <%= user.text_field :surname, :class=>"controls" %>
  </div>
  <div class="control-group">
    <%= user.label :email, "Primary email", :class=>"control-label" %>
    <%= user.text_field :email, :readonly => true, :class=>"controls" %>
  </div>

  <div class="control-group">
    <%= link_to "Reset Password", new_passwordreset_path, :class=> "btn btn-warning btn-medium"%>
  </div>
  <div class="control-group">
    <%= link_to "Delete Account", root_url, :class=> "btn btn-danger btn-medium" %>
  </div>
</div>

app/views/users/_user_settings_tab3.html.erb
<div class="tab-pane" id="tab3">
  <h2>Notification Settings</h2>
  <p>Send Emails (global setting)</p>
  <p>When someone follows my lists</p>
  <p>When someone follows me</p>
  <p>Someone comments on my ideas</p>
  <p>Inspiration newsletter</p>
</div>

app/views/users/_user_settings_tab4.html.erb
<div class="tab-pane" id="tab4">
  <h2>Lists I'm following</h2>
  <ul>
    <% @listings.each do |mylists| %>
        <li>
          <%= mylists.list.name %>
        </li>
    <% end %>
  </ul>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render "edit-tabs-left-panel", :collection => @user %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<h3>All fields are required</h3>
<%= form_for @user do |f| %>

    <%= render "shared/error_messages", :target => @user %>
    <div class = "field">
      <%= f.label :displayname, "Display Name" %>
      <%= f.text_field :displayname %>
    </div>
    <div class = "field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class = "field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class = "field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
      <div class="actions">
        <%= f.submit "Register", :class=>"btn btn-primary" %>
      </div>
<%  end %>

app/views/users/show.html.erb
<div class="hero-unit">
    <h1>
      <% @assets = Asset.gather_current_user_profile(@user.id) %>
      <% if @assets.count > 0  %>
        <%= image_tag(@assets.first.asset.url, :size=> "200x200", :class=> "img-polaroid") %>
          <% else %>
          <%= image_tag "missing.jpg", :size=> "200x200", :class=> "img-polaroid"  %>
      <% end %>
      <%= @user.displayname.capitalize %>
    </h1>
      <i><h4 class="muted"><%= @user.description %></h4></i>
    <div class="row">
          <div class="span12">
            <%= link_to "Facebook", @user.facebook_id, :class=>"btn btn-primary" %> <%= link_to "Twitter", @user.twitter_id, :class=>"btn btn-primary" %> <%=link_to "WWW", @user.website, :class=>"btn btn-primary" %>
          </div>
    </div>
</div>


<div class="row">
  <div class="span8 pull-left">
    <p>Joined <%= @user.created_at.strftime("%B %Y") %></p>
  </div>
</div>
<div class="row">
  <div class="span12">
  <p>Has 15 followers Following over 3,000 </p>
  </div>
</div>
<div class="row">
  <div class="span8 pull-left">
    <p>Recent list/idea/friendship activity</p>
  </div>
  <div class="span4">
      <p>15 lists added Top 5 lists with most ideas</p>
    <ul>
        <% @listings.each do |mylists| %>
            <li>
              <%= mylists.list.name %>
            </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>