config/routes.rb
InspireMe::Application.routes.draw do

  root :to => 'welcome#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  resources :passwordresets
  resources :users
  resources :sessions
  resources :home
  resources :ideas
  resources :lists
  resources :password_resets
  resources :friendships
  resources :listings


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
      list_sort_order(params[:so])
      @newlists = List.newcontent(current_user)
      @newideas = Idea.newcontent(current_user)
      @lastlogged = current_user.last_logged_in

      if @lastlogged.blank?
        current_user.last_logged_in = Time.zone.now
        current_user.save!
      else
        if @lastlogged < 1.day.ago
          current_user.last_logged_in = Time.zone.now
          current_user.save!
        end
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home_left_panel.html.erb
<% content_for :homepage do %>
    <div class="span3">
        <h4 class="muted">Inspiration</h4>
        <ul class="nav nav-tabs nav-stacked">
          <li><%= link_to "Discover" %></li>
        </ul>
        <h4 class="muted">Groups</h4>
        <ul class="nav nav-tabs nav-stacked">
          <li><%= link_to "Special group" %></li>
          <li><%= link_to "Writing" %></li>
          <li><%= link_to "Blogging" %></li>
          <li><%= link_to "Create Group" %></li>
        </ul>
        <h4 class="muted">Lists
          <% if current_user %>
            (<%= @mylists.count %>)
          <% end %>
        </h4>
          <ul class="nav nav-tabs nav-stacked">
            <li><%= link_to 'Create New List', new_list_path %></li>
            <li><%= link_to 'My Lists', lists_path %></li>
            <% if current_user %>
                <% @mylists.each do |l| %>
                    <li><%= link_to l.name, list_path(:id => l.name) %></li>
                <% end %>
            <% end %>
          </ul>
      <h4 class="muted">Friends</h4>
        <ul class="nav nav-tabs nav-stacked">
          <li><%= link_to "My Friends",friendships_path %></li>
          <li><%= link_to "Find Friends", new_friendship_path %></li>
        </ul>
        <h4 class="muted">Notifications</h4>
        <ul class="nav nav-tabs nav-stacked">
          <li><%= link_to "Close Friends (5)" %></li>
          <li><%= link_to "Colleagues(22)" %></li>
          <li><%= link_to "Acquaintances(123)" %></li>
        </ul>
    </div>
<% end %>

<%= content_for :homepage if current_user %>

app/views/home/index.html.erb
<%= image_tag "inspire.png" %>
<div class="row-fluid">
    <div class="span12">
      <h3 class="muted">Works on all these platforms...</h3>
      <%= image_tag "android.png"%>
      <%= image_tag "apple.png"%>
      <%= image_tag "windows.png"%>
      <%= image_tag "linux.png", :size=>"48x48" %>
      <%= image_tag "brw-explorer.png"%>
      <%= image_tag "brw-chrome.png", :size=>"48x48" %>
      <%= image_tag "brw-safari-02.png", :size=>"48x48" %>
    </div>
    <ul class="thumbnails">
      <li class="span4">
        <h3>A place to be inspired</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea </p>
      </li>
      <li class="span4">
        <h3>Organised</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea </p>
      </li>
      <li class="span4">
        <h3>Discover and Share</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea </p>
      </li>
    </ul>
</div>

app/views/home/show.html.erb
<h1 class="page-header">My Home Page</h1>
<p>Lists updated since I last logged on</p>
 <% @newlists.each do |nc| %>
     <%=  nc.name %>
 <% end %>
 <hr />

 <p>New ideas updated since I logged on</p>

 <% @newideas.each do |nc| %>
     <%=  nc.title %>
 <% end %>
 <hr />