config/routes.rb
InspireMe::Application.routes.draw do

  root :to => 'welcome#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  resources :passwordresets
  resources :users
  resources :sessions
  resources :home
  resources :ideas
  resources :lists
  resources :password_resets
  resources :friendships
  resources :listings


end

app/views/layouts/_footer_nav.html.erb
<div class="row-fluid">
  <ul class="nav thumbnails"  >
    <li class="span4">Useful Links
        <%= link_to "About Inspire" %>
        <%= link_to "Contact Us" %>

    </li>
    <li class="span4">Link set 2
        <%= link_to "Our Blog", "http://iwantobeinspired.wordpress.com/" %>
    </li>
    <li class="span4">Link set 3
      <%= link_to "Privacy Policy" %>
    </li>
  </ul>
</div>

app/views/layouts/_front-page-nav.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<div class="nav-collapse">
  <ul class="nav">
    <% if current_user %>
        <% @assets = Asset.gather_current_user_profile(current_user.id) %>
        <%= link_to image_tag(@assets.first.asset.url(:thumb), :class=> 'img-circle'),@assets.first.asset.url(:original) %>
        <%= link_to 'My Home Page',home_path(:id => current_user.displayname) %>
    <% else %>
        <li><%= link_to "Register", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<% content_for :navigation do %>

<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Front Page", root_url %></li>
            </ul>
          <% if current_user %>
              <%= render :partial => 'layouts/user-drop-down-menu' %>
          <% end %>

        </div>
    </div>
  </div>
</div>
<% end %>

<%= content_for :navigation if current_user %>

app/views/layouts/_user-drop-down-menu.html.erb
<div class="btn-group pull-right">
  <a class="btn dropdown-toggle btn-small btn-inverse" data-toggle="dropdown">
    <% @assets = Asset.gather_current_user_profile(current_user.id) %>
    <%= image_tag(@assets.first.asset.url, :size=> "36x36") %>
  <% if current_user.displayname %>
        <%= current_user.displayname %>
    <% else %>
        <%= current_user.email %>
    <% end %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to '<i class="icon-home"></i> Home Page'.html_safe,home_path(:id => current_user.displayname) %></li>
    <li><%= link_to '<i class="icon-pencil"></i> Settings'.html_safe, edit_user_path(:id => current_user.displayname) %></li>
    <li><%= link_to '<i class="icon-user"></i> Public Profile'.html_safe, user_path(:id => current_user.displayname) %></li>
    <li class="divider"></li>
    <li><%= link_to '<i class="icon-off"></i> Log Off'.html_safe, logout_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Inspire Me" %></title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>

<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <%= render 'layouts/messages' %>
        </div>
          <%= render :partial => 'home/home_left_panel' %>
        <div class="span9">
          <%= yield %>
        </div>
      </div>
      <footer>
        <%= render 'layouts/footer_nav' %>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

app/views/layouts/user.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Inspire Me" %></title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
        <%= render 'users/navbar' %>
    </div>
  </div>
</div>
<div id="main" role="main">
  <div class="container">
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
    <footer>
      <%= render 'layouts/footer_nav' %>
    </footer>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

app/views/layouts/welcome.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Inspire Me" %></title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
<div class="container">
  <%= render 'layouts/front-page-nav' %>
</div>
</div>
</div>
<div id="main" role="main">
  <div class="container">
      <div class="row">
        <div class="span12">
          <%= render 'layouts/messages' %>
        </div>
        <div class="span12">
          <%= yield %>
        </div>
      </div>
      <footer>
        <%= render 'layouts/footer_nav' %>
      </footer>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>